import fs from 'node:fs/promises';
import { createReadStream } from 'node:fs';
import path from 'node:path';
import { AppError } from '../utils/AppError.js';

// Development driver: files live on local disk under baseDir.
export function createLocalDriver(baseDir) {
  const root = path.resolve(baseDir);

  // Keys are generated by the server, but guard against path traversal anyway.
  const resolveKey = (key) => {
    const full = path.resolve(root, key);
    if (!full.startsWith(root + path.sep)) throw new Error('Invalid storage key');
    return full;
  };

  return {
    async put(key, buffer) {
      const file = resolveKey(key);
      await fs.mkdir(path.dirname(file), { recursive: true });
      await fs.writeFile(file, buffer, { flag: 'wx' }); // never overwrite an existing file
    },
    async get(key) {
      const file = resolveKey(key);
      try {
        await fs.access(file);
      } catch {
        throw AppError.notFound('File not found');
      }
      return createReadStream(file);
    },
    async delete(key) {
      await fs.rm(resolveKey(key), { force: true });
    },
  };
}
